config/routes.rb
Rails.application.routes.draw do

  resource :session, only: [:new, :create, :destroy]
  resource :user, only: [:show, :new, :create]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, except: [:new, :index] do
    resources :tracks, only: [:new]
  end

  resources :tracks, except: [:new, :index]

end

app/models/album.rb
class Album < ActiveRecord::Base

  validates :title, :rtype, :band_id, presence: true
  validates :rtype, inclusion: { in: %w( Live Studio ) }

  belongs_to(
    :band,
    class_name: "Band",
    foreign_key: :band_id
  )
  has_many(
    :tracks,
    class_name: "Track",
    foreign_key: :album_id,
    dependent: :destroy
  )



end

app/controllers/albums_controller.rb
require 'byebug'
class AlbumsController < ApplicationController
  before_action :ensure_signed_in

  def show
    @album = Album.includes(:tracks).find(params[:id])
    render :show
  end

  def new
    @bands = Band.all
    @album = Album.new
    render :new
  end

  def create
    band_id = Band.find_by(name: params[:bands][:name]).id
    @album = Album.new(album_params.merge(band_id: band_id))

    if @album.save
      flash.now[:notice] = "Album successfully created!"
      redirect_to album_url(@album.id)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def edit
  @bands = Band.all
  @album = Album.includes(:band).find(params[:id])
    render :edit
  end

  def update
    @album = Album.find(params[:id])
    if @album.update(album_params)
      flash[:notice] = "Successfully updated."
      redirect_to album_url(@album.id)
    else
      flash.now[:errors] = @album.errors.full_messages
    end
  end

  def destroy
  @album = Album.find(params[:id])
    @band = @album.band
    if @album.delete
      flash.now[:notice] = "Album DELETED!"
      redirect_to band_url(@band.id)
    else
      flash.now[:errors] = "Failed"
      redirect_to :show
    end
  end

  private

    def album_params
      params.require(:albums).permit(:title, :rtype)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<% if album.persisted? %>
  <% value, action, name, rtype = "patch", albums_url(album.id), album.band.name, album.rtype %>
<% else %>
  <% value, action, name, rtype = "post", albums_url, "", "" %>
<% end %>

<form
  method="post"
  action="<%= action %>">

  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

    <input
      type="hidden"
      name="_method"
      value="<%= value %>">

  <label>
    Which band made this album?
    <select name="bands[name]">
      <option></option>
      <% bands.each do |band| %>
        <option
          value="<%= band.name %>"
          <%= "selected" if name == band.name %>>
        <%= band.name %>
        </option>
      <% end %>
    </select>
  </label>
  <br>

  <label>
    Album Title:
    <input
      type="text"
      name="albums[title]"
      placeholder="In Utero"
      value="<%= album.title %>">
    </input>
  </label>
  <br>

  <p> How was is recorded? </p>
  <label>
    <input
      type="radio"
      name="albums[rtype]"
      value="Studio"
      <%= "checked" if rtype == "Studio" %>>
      Studio
    </input>
  </label>
  <label>
    <input
      type="radio"
      name="albums[rtype]"
      value="Live"
      <%= "checked" if rtype == "Live" %>>
      Live
    </input>
  </label>
  <br>
  <br>

  <button>Submit</button>

</form>

app/views/albums/edit.html.erb
<h1> Edit <%= @album.title %> </h1>

<%= render 'form', album: @album, bands: @bands %>

app/views/albums/new.html.erb
<h1> Add an Album! </h1>

<%= render 'form', album: @album, bands: @bands %>

app/views/albums/show.html.erb
<h1> <%= @album.title %> Album Page </h1>

<form
  method="get"
  action="<%= edit_album_url %>">
    <button>
      Edit Album
    </button>
</form>
  <br>

<table>
  <caption> Track List </caption>
    <colgroup span"3"></colgroup>
    <tr>
      <th>Track Title</th>
      <th>Track Type</th>
      <th>Lyrics (sample)</th>
    </tr>

    <% @album.tracks.each do |track| %>
      <tr>
        <td><%= track.title %></td>
        <td><%= track.track_type %></td>
        <td><% if track.lyrics.nil? %>
              <a href="<%= edit_track_url(track.id) %>">No lyrics, yet. Add lyrics!</a>
            <% else %>
              lyrics_link(track) %>
            <% end %>
        </td>
      </tr>
    <% end %>
</table>
<br>
<br>

  <a href="<%= new_album_track_url(@album.id) %>">Add a Track</a>
<br>
<br>



<form
  method="post"
  action="<%= album_url %>">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
  </input>

  <input
    type="hidden"
    name="_method"
    value="delete">
  </input>

  <button>
    Delete
  </button>
</form>