config/routes.rb
Rails.application.routes.draw do

  resource :session, only: [:new, :create, :destroy]
  resource :user, only: [:show, :new, :create]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, except: [:new, :index] do
    resources :tracks, only: [:new]
  end

  resources :tracks, except: [:new, :index]

end

app/models/band.rb
class Band < ActiveRecord::Base
  validates :name, presence: true

  has_many(
    :albums,
    class_name: "Album",
    foreign_key: :band_id,
    dependent: :destroy
  )
  has_many(
    :tracks,
    :through => :albums,
    source: :tracks
  )

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :ensure_signed_in, except: [:index]

  def index
    @bands = Band.all
    render :index
  end

  def show
    @band = Band.includes(:albums, :tracks).find(params[:id])
    render :show
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      flash.now[:notice] = "Band successfully created!"
      redirect_to band_url(@band.id)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def edit
  @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])
    if @band.update(band_params)
      flash[:notice] = "Successfully updated."
      redirect_to band_url(@band.id)
    else
      flash.now[:errors] = @band.errors.full_messages
    end
  end

  def destroy
    if Band.find(params[:id]).delete
      flash.now[:notice] = "BAND DELETED!"
      redirect_to bands_url
    else
      flash.now[:errors] = "Failed"
      redirect_to :show
    end
  end

  private

    def band_params
      params.require(:bands).permit(:name)
    end
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/_form.html.erb
<% if band.persisted? %>
  <% value, action = "patch", band_url(band.id) %>
<% else %>
  <% value, action = "post", bands_url %>
<% end %>

<form
  method="post"
  action="<%= action %>">

  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

    <input
      type="hidden"
      name="_method"
      value="<%= value %>">

  <label>
    Band Name:
    <input
      type="text"
      name="bands[name]"
      placeholder="Pink Floyd"
      value="<%= band.name %>">
    </input>
  </label>
  <br>
  <br>

  <button> Submit </button>
</form>

app/views/bands/edit.html.erb
<h1> Edit <%= @band.name %> </h1>

<%= render 'form', band: @band %>

app/views/bands/index.html.erb
<h1> All Bands </h1>

<a href="<%= new_band_url %>"> Add a band. </a>
<br>
<br>
<br>

<% @bands.sort_by { |band| band.name }.each do |band| %>
  <a href="<%= band_url(band) %>"><%= band.name %></a>
  <br>
  <br>
<% end %>

app/views/bands/new.html.erb
<h1> Create a new band </h1>

<%= render 'form', band: @band %>

app/views/bands/show.html.erb
<h1> <%= @band.name %> Band Page </h1>

<form
  method="get"
  action="<%= edit_band_url %>">
    <button>
      Edit
    </button>
</form>
  <br>

<table>
  <caption> Album List </caption>
    <colgroup span"3"></colgroup>
    <tr>
      <th>Album Title</th>
      <th>Album Type</th>
      <th># of tracks</th>
    </tr>

    <% @band.albums.each do |album| %>
      <tr>
        <td><a href="<%= album_url(album.id) %>"><%= album.title %><a></td>
        <td><%= album.rtype %></td>
        <td><%= album.tracks.to_a.size %></td>
      </tr>
    <% end %>
</table>
<br>
<br>

  <a href="<%= new_band_album_url(@band.id) %>">Add an Album</a>
<br>
<br>



<form
  method="post"
  action="<%= band_url %>">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">
  </input>

  <input
    type="hidden"
    name="_method"
    value="delete">
  </input>

  <button>
    Delete
  </button>
</form>